const PLANETS = [
	{
		name: 'Earth',
		position: 35,
		material: 'textures/earth.jpg',
		size: 3,
		orbitTime: 0.01,
		sunAxleTime: 0.04,
	},
	{
		name: 'Jupiter',
		position: 55,
		material: 'textures/jupiter.jpg',
		size: 7,
		orbitTime: 0.03,
		sunAxleTime: 0.05,
	},
	{
		name: 'Mars',
		position: 45,
		material: 'textures/mars.jpg',
		size: 1.5,
		orbitTime: 0.07,
		sunAxleTime: 0.07,
	},
	{
		name: 'Mercury',
		position: 15,
		material: 'textures/mercury.jpg',
		size: 1,
		orbitTime: 0.04,
		sunAxleTime: 0.09,
	},
	{
		name: 'Moon',
		position: 105,
		material: 'textures/moon.jpg',
		size: 0.4,
		orbitTime: 0.012,
		sunAxleTime: 0.2,
	},
	{
		name: 'Neptune',
		position: 112,
		material: 'textures/neptune.jpg',
		size: 4,
		orbitTime: 0.024,
		sunAxleTime: 0.156,
	},
	{
		name: 'Saturn',
		position: 75,
		material: 'textures/saturn.jpg',
		size: 6,
		orbitTime: 0.02,
		sunAxleTime: 0.134,
	},
	{
		name: 'Sun',
		position: 0,
		material: 'textures/sun.jpg',
		size: 10,
		orbitTime: 0.0002,
		sunAxleTime: 0.45,
	},
	{
		name: 'Uranus',
		position: 95,
		material: 'textures/uranus.jpg',
		size: 5,
		orbitTime: 0.0121,
		sunAxleTime: 0.23,
	},
	{
		name: 'Venus',
		position: 25,
		material: 'textures/venus.jpg',
		size: 2,
		orbitTime: 0.047,
		sunAxleTime: 0.075,
	},
]
export { PLANETS }
